# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.define "kube1" do |kube1|
    kube1.vm.box = "ubuntu/focal64"
    kube1.vm.hostname = "kube-node1"
    kube1.vm.network "private_network", ip: "192.168.90.10"
    kube1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y
      snap refresh
      snap install microk8s --classic
      usermod -a -G microk8s vagrant
      sudo microk8s add-node -t wYWNPEKKYzmUCgoodIyVNbIwIYBYxICI -l 99999
      microk8s enable dns dashboard helm3 istio prometheus
      sudo ln -s /snap/bin/microk8s.kubectl /snap/bin/kubectl
      sudo apt-get install ansible ansible-lint ansible-doc net-tools -y
    
    SHELL
  end

  config.vm.define "kube2" do |kube2|
    kube2.vm.box = "ubuntu/focal64"
    kube2.vm.hostname = "kube-node2"
    kube2.vm.network "private_network", ip: "192.168.90.20"
    kube2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y
      snap refresh
      snap install microk8s --classic
      usermod -a -G microk8s vagrant
      sudo microk8s join 192.168.90.10:25000/wYWNPEKKYzmUCgoodIyVNbIwIYBYxICI
      microk8s enable dns dashboard helm3 istio prometheus
    SHELL
  end
  
  config.vm.define "kube3" do |kube3|
    kube3.vm.box = "ubuntu/focal64"
    kube3.vm.hostname = "kube-node3"
    kube3.vm.network "private_network", ip: "192.168.90.30"
    kube3.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y
      snap refresh
      snap install microk8s --classic
      usermod -a -G microk8s vagrant
      sudo microk8s join 192.168.90.10:25000/wYWNPEKKYzmUCgoodIyVNbIwIYBYxICI
      microk8s enable dns dashboard helm3 istio prometheus
    SHELL
  end
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  #config.vm.box = "ubuntu/focal64"

  #Waiting timeout 
  config.vm.boot_timeout = 99999

  #Hostname
  #config.vm.hostname = "kube-node2"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  vb.memory = "8192"
  #more custom options here
  vb.cpus = "2"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
 
end
