Vagrant.configure("2") do |config|
  config.vm.box = "openshift/origin-all-in-one"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  vb.memory = "22000"
  #more custom options here
  vb.cpus = "3"
  end

end